### ISSUE TITLE
About memcpy()

### ISSUE THREAD

**Issue by GroLayer** [3gstudent/Eventlogedit-Evolution#1]
When the program runs to memcpy() in  DeleteRecord() on another computer, it crashes.

**Comment by 3gstudent** [comment]
need more detail

**Comment by GroLayer** [comment]
Do you speak Chinese?
用VS2013在本地编译运行正常，但是编译后的exe在放到另一台主机上，程序运行到中途会崩溃，停止工作，检测到是在memcpy()这里停止工作了，换成memmove()也不行。DeleteRecordbyGetHandleEx.cpp这个工程

**Comment by 3gstudent** [comment]
https://github.com/3gstudent/Eventlogedit-evtx--Evolution/blob/master/DeleteRecordofFile.cpp
这个能不能用
