### ISSUE TITLE
issue DeleteRecordofFileEx.exe 

### ISSUE THREAD

**Issue by mcolson1985** [3gstudent/Eventlogedit-Evolution#11]
Hello , I created c:\temp folder and I moved DeleteRecordofFileEx.exe from https://github.com/3gstudent/Eventlogedit-evtx--Evolution/releases/tag/v1.0.0 and when I run CMD run as a Admin and run  I got this see pic:
My goal is to remove one record from eventvwr I wanted to remove one record id and to generate that temp.evtx( after I run this command **DeleteRecordofFileEx.exe System.evtx 7055** but there is no temp.evtx) Could you please help?

![github](https://user-images.githubusercontent.com/65629631/82404814-40883f00-9a30-11ea-9376-07aceb6f2b58.JPG)

**Comment by 3gstudent** [comment]
I've fixed it. Check out the new version.

**Comment by mcolson1985** [comment]
I installed Visual comunity 2015 I downloaded new Eventlogedit-evtx and I compiled the new DeleteRecordofFileEx.cpp to eventlogedit.exe, after I created exe .
when I run it I got this error , see photo am I doing something wrong
![github2](https://user-images.githubusercontent.com/65629631/82527950-ab577a00-9b05-11ea-8429-aa455ff422df.JPG)
please help

**Comment by 3gstudent** [comment]
The file(c:\Windows\system32\winevt\logs\security) is in use.
You can't directly modify it.
This program(DeleteRecordofFileEx.cpp) is used to modify the unoccupied log file.

**Comment by HennelovaZuzana** [comment]
Hello, I have similar problem, but with error 123. What does that mean?

**Comment by HennelovaZuzana** [comment]
I have the same problem. How did you solve this?
