### ISSUE TITLE
openfile error

### ISSUE THREAD

**Issue by HennelovaZuzana** [3gstudent/Eventlogedit-Evolution#16]
Hello,
I get openfile error when running DeleteRecordofFile.exe from commandline.
What does it mean? Any suggestions how to fix it? I dont have the logs open.
Thanx.

**Comment by HennelovaZuzana** [comment]
I have also tried to run the tool after suspending event log services, however it still gives the same error.

**Comment by 3gstudent** [comment]
The file(c:\Windows\system32\winevt\logs\security) is in use.
You can't directly modify it.
This program(DeleteRecordofFileEx.cpp) is used to modify the unoccupied log file.

**Comment by 3gstudent** [comment]
https://github.com/3gstudent/Eventlogedit-evtx--Evolution/blob/master/DeleteRecordofFile.cpp#L436

**Comment by HennelovaZuzana** [comment]
Thanx, I see now why the error is raised.

But shouldnt suspending the log services work? I assume those are the only ones which are directly accessing the log files. I tried both SuspendorResumeTid.cpp and SuspendorResumeTidEx.cpp and i also tried Phant0m to stop logging threads, however it didnt help. 

It didnt even work on copied logs, which again I believe are not opened by any other service. But that is only assumption.

how can I make the log file unoccupied for this tool to work?

**Comment by 3gstudent** [comment]
run this:
`wevtutil.exe epl Setup c:\test\Setup.evtx`
